import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { GlobalNav } from '../ui/globalNav';
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-gray-1100 overflow-y-scroll bg-[url('/grid.svg')] pb-36">
        <GlobalNav />
        <div className="w-full h-full">{children}</div>
      </body>
    </html>
  )
}
